---
- name: Set up debian box
  hosts: all
  roles:
    - system
    - editor
    - terminal
    - role: artis3n.tailscale.machine
      when: "'production' in group_names"
      tags: tailscale
    - notifications
    - file_manager
    - machine_wake
    - hifis.toolkit.unattended_upgrades
    - drift_management
