---
- name: Set up debian box
  hosts: all
  roles:
    - system
    - role: disks
      when: "'vm' not in group_names and 'pi' not in group_names"
    - editor
    - mounts
    - backups
    - firewall
    - containers
    - terminal
    - role: artis3n.tailscale.machine
      when: "'production' in group_names"
      tags: tailscale
    - notifications
    - file_manager
    - reverse_proxy
    - drift_management
