---
- name: Restart autofs
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  become: true
  loop: "{{ enabled_services }}"
- name: Clear nfsidmap cache
  become: true
  ansible.builtin.command:
    cmd: nfsidmap -c
  changed_when: true
