---
- name: Set the hostname
  when: domain_name is defined
  become: true
  ansible.builtin.hostname:
    name: "{{ domain_name }}"
- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ timezone }}"
- name: Remove mail_badpass from sudoers
  ansible.builtin.replace:
    group: root
    mode: "0440"
    owner: root
    path: /etc/sudoers
    regexp: (^Defaults.*mail_badpass$)|(\,mail_badpass)
    replace: ""
    validate: /usr/sbin/visudo -cf %s
  become: true
- name: Adding pwfeedback
  ansible.builtin.copy:
    content: |
      Defaults        pwfeedback
    dest: /etc/sudoers.d/02-pwfeedback
    group: root
    mode: "0440"
    owner: root
    validate: /usr/sbin/visudo -cf %s
  become: true
- name: Ensure /root/.ssh exists
  become: true
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: "0700"
- name: Set up root SSH key
  become: true
  block:
    - name: Copy root private key
      ansible.builtin.copy:
        src: "{{ inventory_hostname }}/vault_{{ ssh_key_name }}"
        dest: "/root/.ssh/{{ ssh_key_name }}"
        owner: root
        group: root
        mode: "0600"
    - name: Copy root public key
      ansible.builtin.template:
        src: "{{ inventory_hostname }}/{{ ssh_key_name }}.pub.j2"
        dest: "/root/.ssh/{{ ssh_key_name }}.pub"
        owner: root
        group: root
        mode: "0644"
  rescue:
    - name: Generate root keys
      community.crypto.openssh_keypair:
        path: "/root/.ssh/{{ ssh_key_name }}"
        type: ed25519
        owner: root
        group: root
        comment: "root@{{ inventory_hostname }}"
- name: Configure systemd-journald to persist storage
  ansible.builtin.include_role:
    name: persist_journald
    apply:
      become: true
