---
- name: Configure auto.master
  become: true
  ansible.builtin.template:
    src: auto.master.j2
    dest: /etc/auto.master
    group: root
    mode: "0600"
    owner: root
  notify: Restart autofs
- name: Configure auto.misc
  become: true
  ansible.builtin.template:
    src: auto.misc.j2
    dest: /etc/auto.misc
    group: root
    mode: "0600"
    owner: root
  notify: Restart autofs
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
