---
- name: Grant caddy user access to fetch Tailscale certificate
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/tailscaled
    regexp: "^TS_PERMIT_CERT_UID="
    line: "TS_PERMIT_CERT_UID=caddy"
  notify: Restart tailscaled
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    group: caddy
    mode: "0640"
    owner: caddy
  notify: Restart caddy
